[package]
name = "battleship"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "1.3"
colored = "2.1"
crossterm = "0.27"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
thiserror = "2.0"